# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
x=np.arange(0,10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
x=np.arange(0,10).reshape(2,5)
y=np.ones(10).reshape(2,5)
z= np.vstack((x,y))
z.astype(int)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
x=np.arange(0,10).reshape(2,5)
y=np.ones(10).reshape(2,5)
z=np.hstack((x,y))
z.astype(int)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
#x=np.arange(0,10).reshape(2,5)
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

## Question:7

### Create 5x5 an array and find the square of an array?

In [4]:
x=np.arange(25).reshape(5,5)
np.square(x)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [5]:
x=np.arange(30).reshape(5,6)
np.mean(x)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [6]:
x=np.arange(30).reshape(5,6)
np.std(x)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [7]:
np.median(x)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [8]:
x=np.arange(30).reshape(5,6)
np.transpose(x)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [9]:
x=np.arange(16).reshape(4,4)
np.trace(x)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [10]:
x=np.arange(16).reshape(4,4)
np.linalg.det(x)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [11]:
x=np.arange(111)
print("5th percentile of array: ",
np.percentile(x,5))
print("95th percentile of array: ",
np.percentile(x,95))


5th percentile of array:  5.5
95th percentile of array:  104.5


## Question:15

### How to find if a given array has any null values?

In [12]:
x=np.arange(0,5)
np.isnan(x)

array([False, False, False, False, False])